sudo: false
language: python

python:
  - "3.6"

before_install:
  # install libspatialindex necessary for osmnx
  - curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
  - cd spatialindex-src-1.8.5
  - ./configure
  - sudo make install
  - sudo ldconfig
  - cd ..

install: pip install tox-travis

script: tox
